createJavaScriptNode --> createScriptProcessor
I was not getting any audio due to

  TypeError: context.createJavaScriptNode is not a function, audio.js:47

in Firefox 28/29 and Chrome 31. Apparently createJavaScriptNode has been renamed to createScriptProcessor[1].  Making this change fixed things for me in Firefox and Chrome.

[1] https://developer.mozilla.org/en-US/docs/Web/API/AudioContext.createJavaScriptNode